runtime: nodejs20
service: rowx-backend-service # 👈 change this to your service name

instance_class: F1 # 👈 smallest, free-tier eligible instance
automatic_scaling:
  min_instances: 0 # 👈 don't keep any instances running when idle
  max_instances: 1 # 👈 max 1 instance to prevent scaling up costs
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
  max_idle_instances: 1
  min_idle_instances: 0

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  MONGODB_URI: "projects/careful-result-451013/secrets/MONGODB_URI/versions/latest"
  EMAIL_USER: "projects/careful-result-451013/secrets/EMAIL_USER/versions/latest"
  EMAIL_PASS: "projects/careful-result-451013/secrets/EMAIL_PASS/versions/latest"
