name: Deploy to Google Cloud App Engine

on:
  push:
    branches:
      - master  # or your deployment branch

permissions:
  contents: 'read'
  id-token: 'write'  # Required for Workload Identity Federation

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to App Engine
        run: gcloud app deploy --quiet
